server {
    listen 80;
    listen [::]:80;
    server_name localhost;
    root /var/www/public; # 👈 Laravel က public folder ထဲကနေ ပွင့်ရတာမို့လို့ပါ

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php index.html;

    charset utf-8;

    # 👈 ဒီအပိုင်းက Laravel Routing အတွက် အသက်ပါပဲ (404 နဲ့ 500 ကို ရှင်းပေးမယ့်ကုဒ်)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}